/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#61d8d7",
        "on-secondary-fixed-variant": "#005235",
        "surface-container": "#eaefee",
        "surface-variant": "#dee4e3",
        "on-secondary-fixed": "#002113",
        "surface-container-highest": "#dee4e3",
        "secondary": "#206b4b",
        "on-surface": "#171d1c",
        "secondary-fixed": "#a9f2ca",
        "surface-container-low": "#eff5f4",
        "tertiary-container": "#e88a5b",
        "tertiary-fixed-dim": "#ffb693",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "primary": "#006a69",
        "surface-dim": "#d6dbda",
        "primary-fixed": "#80f5f3",
        "on-tertiary-fixed": "#351000",
        "on-primary-fixed-variant": "#00504f",
        "on-error": "#ffffff",
        "inverse-primary": "#61d8d7",
        "on-tertiary-container": "#632500",
        "secondary-container": "#a6efc7",
        "whatsapp-green": "#25D366",
        "outline": "#6d7a79",
        "tertiary": "#95491f",
        "on-secondary": "#ffffff",
        "on-primary-container": "#004040",
        "outline-variant": "#bcc9c8",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#8dd6af",
        "on-primary-fixed": "#002020",
        "surface": "#f5faf9",
        "tertiary-fixed": "#ffdbcc",
        "surface-tint": "#006a69",
        "on-surface-variant": "#3d4949",
        "on-background": "#171d1c",
        "primary-container": "#32b3b2",
        "on-primary": "#ffffff",
        "surface-container-high": "#e4e9e8",
        "inverse-surface": "#2c3131",
        "on-tertiary": "#ffffff",
        "background": "#f5faf9",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ecf2f1",
        "surface-light": "#F8FAFC",
        "on-secondary-container": "#266f4f",
        "on-tertiary-fixed-variant": "#773209",
        "surface-bright": "#f5faf9",
        "text-muted": "#475569"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "5rem",
        "gutter": "1.5rem",
        "container-max": "1280px",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "heading": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
